Fix error
Causing the error 

"/rbd/pnpm-volume/5d2b51bf-c2fe-43df-9fd7-bc599f7acbfe/node_modules/.registry.npmjs.org/myanimelists/1.0.1/node_modules/myanimanimelists/src/services/Info.js:42
            .then(async (items) => {
                        ^
SyntaxError: Unexpected token ("